# Generated by Django 4.2.19 on 2025-03-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
