# Generated by Django 4.2.19 on 2025-03-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_task_category_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='task',
        ),
    ]
